# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.cache/wt [current_project]
set_property parent.project_path D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo d:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/imports/Cam_OV7670_Vivado/i2c_sender.vhd.vhd
  D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/imports/Cam_OV7670_Vivado/ov7670_registers.vhd.vhd
  D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/imports/Cam_OV7670_Vivado/debounce.vhd.vhd
  D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/imports/Cam_OV7670_Vivado/ov7670_capture.vhd.vhd
  D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/imports/Cam_OV7670_Vivado/vga.vhd.vhd
  D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/imports/Cam_OV7670_Vivado/clocking.vhd.vhd
  D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/imports/Cam_OV7670_Vivado/ov7670_controller.vhd.vhd
  D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/imports/Cam_OV7670_Vivado/ov7670_top.vhd.vhd
}
read_ip -quiet D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/constrs_1/imports/Cam_OV7670_Vivado/zed_board.xdc.xdc
set_property used_in_implementation false [get_files D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/constrs_1/imports/Cam_OV7670_Vivado/zed_board.xdc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top ov7670_top -part xc7z020clg484-1


write_checkpoint -force -noxdef ov7670_top.dcp

catch { report_utilization -file ov7670_top_utilization_synth.rpt -pb ov7670_top_utilization_synth.pb }
