# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard_mzedboard_master_XDC_RevC_D_v3aster_XDC_RevC_D_v3.xdc

# IP: ip/frame_buffer_rgb565/frame_buffer_rgb565.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==frame_buffer_rgb565 || ORIG_REF_NAME==frame_buffer_rgb565} -quiet] -quiet
