# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Data/FYP/fyp/fyp.srcs/sources_1/ip/frame_buffer_rgb565/frame_buffer_rgb565.xci
# IP: The module: 'frame_buffer_rgb565' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Data/FYP/fyp/fyp.gen/sources_1/ip/frame_buffer_rgb565/frame_buffer_rgb565_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer_rgb565'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Data/FYP/fyp/fyp.srcs/sources_1/ip/frame_buffer_rgb565/frame_buffer_rgb565.xci
# IP: The module: 'frame_buffer_rgb565' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Data/FYP/fyp/fyp.gen/sources_1/ip/frame_buffer_rgb565/frame_buffer_rgb565_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer_rgb565'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
