set_property SRC_FILE_INFO {cfile:D:/work/2021_ZedBoard_Cam/Cam_OV7670_Vivado/ov7670_cam/ov7670_cam.srcs/constrs_1/imports/Cam_OV7670_Vivado/zed_board.xdc.xdc rfile:../../../ov7670_cam.srcs/constrs_1/imports/Cam_OV7670_Vivado/zed_board.xdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    Y9 [get_ports {   clk100 } ]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	Y21	[get_ports {	vga_blue[0]	}	]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	Y20	[get_ports {	vga_blue[1]	}	]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AB20	[get_ports {	vga_blue[2]	}	]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AB19	[get_ports {	vga_blue[3]	}	]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AB22	[get_ports {	vga_green[0]	}	]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AA22	[get_ports {	vga_green[1]	}	]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AB21	[get_ports {	vga_green[2]	}	]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AA21	[get_ports {	vga_green[3]	}	]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	V20	[get_ports {	vga_red[0]	}	]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	U20	[get_ports {	vga_red[1]	}	]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	V19	[get_ports {	vga_red[2]	}	]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	V18	[get_ports {	vga_red[3]	}	]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AA19	[get_ports {	vga_hsync	}	]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	Y19	[get_ports {	vga_vsync	}	]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	W8	[get_ports {	OV7670_PWDN	}	]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	V8	[get_ports {	OV7670_RESET}	]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	Y11	[get_ports {	OV7670_D[0]	}	]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AB11 [get_ports {    OV7670_D[1]	}	]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AA11 [get_ports {	OV7670_D[2]	}	]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AB10 [get_ports {	OV7670_D[3]	}	]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	Y10	[get_ports {	OV7670_D[4]	}	]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AB9	[get_ports {	OV7670_D[5]	}	]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	V12	[get_ports {	OV7670_D[6]	}	]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AA8	[get_ports {	OV7670_D[7]	}	]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	W12	[get_ports {	OV7670_XCLK	}	]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	AA9	[get_ports {	OV7670_PCLK	}	]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	W11	[get_ports {	OV7670_HREF	}	]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	W10	[get_ports {	OV7670_VSYNC}	]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	V10	[get_ports {	OV7670_SIOD	}	]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	V9	[get_ports {	OV7670_SIOC}	]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	T22	[get_ports {	LED[0]	}	]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	T21	[get_ports {	LED[1]	}	]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	U22	[get_ports {	LED[2]	}	]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	U21	[get_ports {	LED[3]	}	]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	V22	[get_ports {	LED[4]	}	]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	W22	[get_ports {	LED[5]	}	]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	U19	[get_ports {	LED[6]	}	]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	U14	[get_ports {	LED[7]	}	]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	T18	[get_ports {	btn	}	]
